backend:
  name: git-gateway
  branch: netlify-test

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "projects"
    label: "Projects"
    extension: "json"
    files:
      - file: "src/lib/backend/projects.json"
        label: "project"
        name: "project"
        fields:
          - label: "Project List"
            name: "projectlist"
            widget: "list"
            fields:
              - { label: "date", name: "date", widget: "string" }
              - { label: "image", name: "image", widget: "image" }
              - { label: "title", name: "title", widget: "string" }
              - { label: "text", name: "text", widget: "markdown" }
