backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "project"
    label: "Project"
    folder: "src/routes/projects"
    create: true
    fields:
      - { label: "date", name: "date", widget: "string" }
      - { label: "image", name: "date", widget: "image" }
      - { label: "title", name: "date", widget: "string" }
      - { label: "text", name: "date", widget: "markdown" }
