---
backend:
  name: git-gateway
  branch: netlify-test
media_folder: static/img
public_folder: /img
collections:
  - name: projects
    label: Projekty
    extension: json
    editor:
      preview: false
    files:
      - file: src/lib/backend/projects.json
        label: Lista projektów
        name: projectlist
        fields:
          - label: Projekty
            name: projects
            widget: list
            fields:
              - label: Data
                name: date
                widget: string
              - label: Link do obrazu
                name: image
                widget: image
                media_folder: /static/img/projects
              - label: Tytuł
                name: title
                widget: string
              - label: Opis
                name: text
                widget: text
  - name: homepage
    label: Strona główna
    extension: json
    editor:
      preview: false
    files:
      - file: src/lib/backend/home.json
        label: Wpisy na stronie głównej
        name: home
        fields:
          - label: O nas
            name: aboutUs
            widget: markdown
          - label: Warte Uwagi
            name: noteworthy
            widget: list
            fields:
              - label: Link
                name: href
                widget: string
              - label: Link do obrazu
                name: imgSrc
                widget: image
              - label: Podpis do obrazu
                name: imgAlt
                widget: string
              - label: Tytuł
                name: text
                widget: string
          - label: Nasze Atuty
            name: strengths
            widget: list
            fields:
              - label: Nazwa atutu
                name: name
                widget: string
              - label: Opis
                name: description
                widget: text
              - label: Link do ikony
                name: icon
                widget: image
              - label: Podpis do ikony
                name: iconAlt
                widget: string
          - label: Nasze Sekcje
            name: sections
            widget: list
            fields:
              - label: Nazwa sekcji
                name: name
                widget: string
              - label: Opis
                name: description
                widget: text
              - label: Link do ikony
                name: icon
                widget: image
              - label: Podpis do ikony
                name: iconAlt
                widget: string
  - name: forstudent
    label: Dla ucznia
    extension: json
    editor:
      preview: false
    files:
      - file: src/lib/backend/forstudent.json
        label: Wpisy na stronie dla ucznia
        name: forstudent
        fields:
          - label: Dla ucznia
            name: services
            widget: list
            fields:
              - label: Tytuł
                name: name
                widget: string
              - label: Opis
                name: description
                widget: text
              - label: Link
                name: href
                widget: string
              - label: Link do ikony
                name: imgSrc
                widget: image
              - label: Tekst przycisku
                name: btnText
                widget: string
              - label: Tag
                name: tag
                widget: select
                default:
                  label: Brak
                  value: ""
                options:
                  - label: Brak
                    value: ""
                  - label: Nowe
                    value: new
                  - label: Już wkrótce
                    value: soon
