backend:
  name: git-gateway
  branch: netlify-test

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "projects"
    label: "Projects"
    extension: "json"
    files:
      - file: "src/lib/backend/projects.json"
        label: "Project List"
        name: "projectlist"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Data", name: "date", widget: "string" }
              - { label: "Link do obrazu", name: "image", widget: "image" }
              - { label: "Tytuł", name: "title", widget: "string" }
              - { label: "Opis", name: "text", widget: "markdown" }
  - name: "routes"
    label: "routes"
    extension: "json"
    files:
      - file: "src/lib/backend/routes.json"
        label: "Route List"
        name: "routelist"
        fields:
          - label: "Route"
            name: "route"
            widget: "list"
            fields:
              - { label: "Route", name: "route", widget: "string" }
              - { label: "Route Name", name: "routename", widget: "string" }
  - name: "homepage"
    label: "Homepage"
    extension: "json"
    files:
      - file: "src/lib/backend/home.json"
        label: "Home"
        name: "home"
        fields:
          - { label: "O nas", name: "aboutUs", widget: "string" }
          - label: "Warte Uwagi"
            name: "noteworthy"
            widget: "list"
            fields:
              - { label: "Link", name: "href", widget: "string" }
              - { label: "Link do obrazu", name: "imgSrc", widget: "image" }
              - { label: "Podpis do obrazu", name: "imgAlt", widget: "string" }
              - { label: "Tytuł", name: "text", widget: "string" }
          - label: "Nasze Atuty"
            name: "strengths"
            widget: "list"
            fields:
              - { label: "Nazwa atutu", name: "name", widget: "string" }
              - { label: "Opis", name: "description", widget: "markdown" }
              - { label: "Link do ikony", name: "icon", widget: "image" }
              - { label: "Podpis do ikony", name: "iconAlt", widget: "string" }
          - label: "Nasze Sekcje"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Nazwa sekcji", name: "name", widget: "string" }
              - { label: "Opis", name: "description", widget: "markdown" }
              - { label: "Link do ikony", name: "icon", widget: "image" }
              - { label: "Podpis do ikony", name: "iconAlt", widget: "string" }
